CREATE TABLE IF NOT EXISTS product_service.product
(
    uuid uuid NOT NULL,
    calories integer,
    carbohydrates double precision,
    dt_create timestamp without time zone,
    dt_update timestamp without time zone,
    fats double precision,
    proteins double precision,
    title character varying(255) COLLATE pg_catalog."default",
    weight integer,
    CONSTRAINT product_pkey PRIMARY KEY (uuid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS product_service.product
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS product_service.recipe
(
    uuid uuid NOT NULL,
    dt_create timestamp without time zone,
    dt_update timestamp without time zone,
    title character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT recipe_pkey PRIMARY KEY (uuid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS product_service.recipe
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS product_service.composition
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    weight integer,
    product_id uuid NOT NULL,
    recipe_id uuid,
    CONSTRAINT composition_pkey PRIMARY KEY (id),
    CONSTRAINT fk9kvv9xsvv66sjlwl0y2kdrg9o FOREIGN KEY (product_id)
        REFERENCES product_service.product (uuid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fknc8fbntg19wuc7gawub6hh9kd FOREIGN KEY (recipe_id)
        REFERENCES product_service.recipe (uuid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT composition_weight_check CHECK (weight >= 1)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS product_service.composition
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS product_service.profile
(
    uuid uuid NOT NULL,
    activity_type character varying(255) COLLATE pg_catalog."default",
    dt_birthday timestamp without time zone,
    dt_create timestamp without time zone,
    dt_update timestamp without time zone,
    height integer,
    sex character varying(255) COLLATE pg_catalog."default",
    target double precision,
    user_dt_create timestamp without time zone,
    user_dt_update timestamp without time zone,
    user_uuid uuid,
    weight double precision,
    CONSTRAINT profile_pkey PRIMARY KEY (uuid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS product_service.profile
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS product_service.journal_food
(
    uuid uuid NOT NULL,
    dt_create timestamp without time zone,
    dt_supply timestamp without time zone,
    dt_update timestamp without time zone,
    weight integer,
    product_id uuid,
    profile_uuid uuid,
    recipe_id uuid,
    CONSTRAINT journal_food_pkey PRIMARY KEY (uuid),
    CONSTRAINT fkaj3ocp39dod1nlri9o2t9ia3a FOREIGN KEY (product_id)
        REFERENCES product_service.product (uuid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkeat5cyf84q32immgj3uf1qi2o FOREIGN KEY (profile_uuid)
        REFERENCES product_service.profile (uuid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkeufnwkoukpg4147w4b6l4t3xq FOREIGN KEY (recipe_id)
        REFERENCES product_service.recipe (uuid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS product_service.journal_food
    OWNER to postgres;