CREATE TABLE IF NOT EXISTS report_service.report
(
    uuid uuid NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    dt_create timestamp without time zone,
    dt_update timestamp without time zone,
    dt_from timestamp without time zone,
    dt_to timestamp without time zone,
    status character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default",
    user_uuid uuid,
    CONSTRAINT report_pkey PRIMARY KEY (uuid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS report_service.report
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS report_service.binary_report
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    rep_array bytea,
    report_uuid uuid,
    CONSTRAINT binary_report_pkey PRIMARY KEY (id),
    CONSTRAINT fkslacm3e1ul98d921b4e3yt1h0 FOREIGN KEY (report_uuid)
        REFERENCES report_service.report (uuid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS report_service.binary_report
    OWNER to postgres;